name: 0.1$(Rev:.r)

trigger:
  branches:
    include:
      - "master"
pr: none

variables:
  repoWorkingDir: "$(Build.SourcesDirectory)"
  dockerFileBasePath: "$(Build.SourcesDirectory)"

stages:
  - template: templates/build-docker.yml
    parameters:
      buildName: "use_app"
      repoWorkingDir: "$(repoWorkingDir)"
      projectDir: "use_app"
      containerRegistry: "$(containerRegistry)"
      dockerfilePath: "$(dockerFileBasePath)/use_app/Dockerfile"
      buildArguments: |
        --build-arg BuildId="$(Build.BuildId)"
      tag: $(tag)
